CREATE TABLE `scheduler` (
    `id` BIGINT	AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `name`	VARCHAR(20)	NULL,
    `contents`	VARCHAR(255)	NULL,
    `password`	VARCHAR(20)	NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL
);

